### ISSUE TITLE
Crashes if token doesn't have admin invitations?

### ISSUE THREAD

**Issue by lionirdeadman** [bilelmoussaoui/fps#5]
```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib64/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/var/home/DaSH/Projects/fps/fps/utils.py", line 64, in update_repo
    pending_invitations = gh_repo.get_pending_invitations().totalCount
  File "/var/home/DaSH/.local/share/virtualenvs/fps-cOdfMnes/lib/python3.9/site-packages/github/PaginatedList.py", line 149, in totalCount
    headers, data = self.__requester.requestJsonAndCheck(
  File "/var/home/DaSH/.local/share/virtualenvs/fps-cOdfMnes/lib/python3.9/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/var/home/DaSH/.local/share/virtualenvs/fps-cOdfMnes/lib/python3.9/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 403 {"message": "Must have admin rights to Repository.", "documentation_url": "https://docs.github.com/rest/reference/repos#list-repository-invitations"}
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/home/DaSH/.local/share/virtualenvs/fps-cOdfMnes/bin/fps", line 33, in <module>
    sys.exit(load_entry_point('fps', 'console_scripts', 'fps')())
  File "/var/home/DaSH/.local/share/virtualenvs/fps-cOdfMnes/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/var/home/DaSH/.local/share/virtualenvs/fps-cOdfMnes/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/var/home/DaSH/.local/share/virtualenvs/fps-cOdfMnes/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/var/home/DaSH/.local/share/virtualenvs/fps-cOdfMnes/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/var/home/DaSH/.local/share/virtualenvs/fps-cOdfMnes/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/var/home/DaSH/.local/share/virtualenvs/fps-cOdfMnes/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/var/home/DaSH/Projects/fps/fps/cli.py", line 40, in refresh
    app.refresh_cache()
  File "/var/home/DaSH/Projects/fps/fps/application.py", line 83, in refresh_cache
    pool.map(update_repo, _repos)
  File "/usr/lib64/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib64/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
github.GithubException.GithubException: 403 {"message": "Must have admin rights to Repository.", "documentation_url": "https://docs.github.com/rest/reference/repos#list-repository-invitations"}
```

This seems to be the responsible code https://github.com/bilelmoussaoui/fps/blob/master/fps/application.py#L83

Token has `repo` and `admin:read:org`

**Comment by bilelmoussaoui** [comment]
I think we actually don't really need a token at all... It's just the github package we use is...not great
```
curl \
  -H "Accept: application/vnd.github.v3+json" \
  https://api.github.com/orgs/flathub/repos
```
works just fine. 

Maybe we can just use requests here and drop the github package dependency

**Comment by lionirdeadman** [comment]
Been looking into why and I think this might actually be why, it seems to want pending invitations in a couple of places.
https://github.com/bilelmoussaoui/fps/blob/master/fps/application.py#L89

**Comment by bilelmoussaoui** [comment]
Ah I see. I guess we can keep the env variable only when you have admin rights and fallback to a simple http call. If the env variable doesn't exists, we just set the pending invitations number to None and hide it from the template
